<?php


require_once (__DIR__ . '/../Models/PropuestaModel.php');
use \PHPUnit\Framework\TestCase;

class PropuestaModelTest extends TestCase {
    public function proveedorIngresarPropuesta() {
        return [
            'CP-001' => [True, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-002' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javi", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-003' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh Beckenbauer Colonense  Wolfe­schlegel­stein­hausen­berger­dorff Dixon Humilde", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-004' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-005' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-006' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-1230000000000000000", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-007' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-008' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "abc", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-009' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "6676", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-010' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "6676188889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-011' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-012' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "s@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-013' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh.humilde.colonense.dixon@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-014' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-015' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "abcd"]],
            'CP-016' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in "]],
            'CP-017' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => ""]],
            'CP-020' => [False, ["nombre_pro" => "Proy", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-022' => [False, ["nombre_pro" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-023' => [False, ["nombre_pro" => "", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-024' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cint", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-025' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-026' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-027' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-11-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-028' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2029-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-029' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-030' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "3:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-031' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "22:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-032' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "21:00", "hora_final_pro" => "9:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-033' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-034' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "22:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-035' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "4:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-036' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-037' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "a", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-038' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "-52", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-039' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "205", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-040' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-041' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Lim", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-042' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-043' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-044' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Rec", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-045' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-046' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "", "materiales_pro" => "Bolsas de basura y guantes", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-047' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Bol", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-048' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],
            'CP-049' => [False, ["nombre_pro" => "Limpieza de Playa", "lugar_pro" => "Cinta Costera", "fecha_pro" =>  "2020-12-31", "hora_inicio_pro" => "7:00", "hora_final_pro" => "21:00", "participantes_pro" => "50", "describ_pro" => "Limpiar cinta costera para contribuir con el ambiente", "objetivo_pro" => "Recoger toda la basura", "materiales_pro" => "", "nombre_encarg" => "Javier Singh", "cedula_encarg" => "3-567-123", "telefono_encarg" => "66761889", "correo" => "javier.singh@utp.ac.pa", "perfil_estu_pro" => "Estudiantes guapos"]],

        ];
    }

    /**
     * @dataProvider proveedorIngresarPropuesta
     */

    public function testIngresarPropuesta($resultado_esperado, $datos) {
        $propuestaModel = new PropuestaModel();
        $this->assertEquals($resultado_esperado, $propuestaModel->insertar_propuesta($datos));

    }

    public function proveedorIngresarAnioFacultad() {
        return [
            'CP-001' => ["facultad"=>["1","3","4"], "anio"=>["1","2"],[3,2]],
            'CP-019' => ["facultad"=>["1","3","4"], "anio"=>[],[3,0]],
            'CP-020' => ["facultad"=>[], "anio"=>["1","2"],[0,2]]
        ];
    }

    /**
     * @dataProvider proveedorIngresarAnioFacultad
     */
    public function testIngresarAnioFacultad($datos1,$datos2,$resultado_esperado){
        $propuestaModel = new PropuestaModel();
        foreach($resultado_esperado as $resultado){
            $this->assertContains($resultado,$propuestaModel->insertar_facultad_anio_propuesta($datos1,$datos2));
        }

    }


    public function proveedorRechazarPropuesta(){
       return [
           'CP-050' => [1, "Información Insuficiente", True],
           'CP-051' => [1, "Poco", False],
           'CP-052' => [1, "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi nisi turpis, pretium quis dictum id, eleifend at justo. Cras dignissim tortor nec molestie mollis. Quisque dignissim blandit sapien, quis accumsan enim elementum ut. Donec venenatis velit erat, a vestibulum justo scelerisque et. Aliquam erat volutpat.", False],
           'CP-053' => [1, "", False]
       ];

    }

    /**
     * @dataProvider proveedorRechazarPropuesta
     */

     public function testRechazarPropuesta($id_propuesta, $motivo, $resultado_esperado){
        $propuestaModel =new PropuestaModel();
        $this->assertEquals($resultado_esperado, $propuestaModel->rechazar_propuesta($id_propuesta, $motivo));

     }

    public function proveedorAprobarPropuesta(){
        return [
            'ID Númerico' => [True, 1],
            'ID String' => [False, "abcd"]
        ];

    }


     /**
     * @dataProvider proveedorAprobarPropuesta
     */
    public function testAprobarPropuesta($resultado_esperado, $id_propuesta) {
        $propuestaModel = new PropuestaModel();
        $this->assertEquals($resultado_esperado, $propuestaModel->aprobar_propuesta($id_propuesta));
    }
}